config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get '/home/input_data', to: 'home#input_data', as: :input_data
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def input_data
    value = params[:option].downcase
    values = value.split(' ')
    loaded_data = LOADED_DATA

    if values.count > 1
      sorted_data = []
      values.each do |value|
        data = sorted_data.present? ? sorted_data : loaded_data
        sorted_data = search_engine(value, data)
      end

      @all_values = sorted_data
    else
      search_engine(value, loaded_data)
    end
  end

  def search_engine(value, data)
    @all_values = []
    options = ['Name', 'Type', 'Designed by']

    options.each do |option|
      sorted_data = data.select do |opt|
        next if @all_values.include?(opt)
        opt[option].downcase.include?(value)
      end
      sorted_data.each { |val| @all_values << val}
    end

    @all_values
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="index-style">
  <h1 class="index-title">Hello, this is simple search app with preload data.</h1>
  <%= form_tag(input_data_path, method: :get) do %>
    <a title="Then fill in what you are looking for according to the chosen option.">
      <%= text_field_tag :option, '', class: 'index-form-text' %>
    </a>
    <%= submit_tag 'Search', class: 'index-submit-select' %>
  <% end %>
</div>

app/views/home/input_data.html.erb
<div class="table-page">
  <table>
    <% if !@all_values.present? %>
      <div class="alert-dialog">Ooops! There's nothing here, try something else.</div>
    <% else %>
      <thead>
      <tr>
        <th>Name</th>
        <th>Type</th>
        <th>Designed By</th>
      </tr>
      </thead>
      <tbody>
      <% @all_values.each do |value| %>
        <tr>
          <td>
            <%= value["Name"] %>
          </td>
          <td>
            <%= value["Type"] %>
          </td>
          <td>
            <%= value["Designed by"] %>
          </td>
        </tr>
      <% end %>
      </tbody>
    <% end %>
  </table>

  <br>

  <button class="index-submit-select"><%= link_to 'Back to search', root_path %></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>